### ISSUE TITLE
Does this still work? Please contact me. 

### ISSUE THREAD

**Issue by Zaptified** [edde746/tiktok-uploader#4]
Hello, I’m interested in this and I’d like to know if it still works or if you could get it to work, and if you could add some features like an automatic account creator & poster. I could pay you to do this. Please contact me on discord: luigitog or telegram @StixPack
Thank you!

**Comment by edde746** [comment]
Try it yourself, but as per #3 it seems that some things need updating. Not interested in paid work related to this.
